"""Pure-Python core: the luminance-blend algorithm, no ``bpy`` import anywhere.

Re-exports the public API so callers can do ``from mask_luminance import core``
and ``core.MaskChannel(...)`` etc., matching the layering convention used by
other Genies Blender addons (core/ = testable logic, scene/ = bpy glue,
operators.py = thin adapter).
"""

from .blend import (
    DEFAULT_REGION_PALETTE,
    DEFAULT_SELF_LOCALITY_RADIUS,
    GATE_MODES,
    MaskChannel,
    apply_blend_group,
    apply_blending_radius,
    apply_mask_channel,
    build_correction_target,
    build_local_diffuse_target,
    build_region_gate,
    color_id_mask,
    composite_correction_targets,
    composite_skin_envelope,
    composite_weights,
    compute_channel_gate,
    compute_channel_soft_mask,
    correct_region,
    extract_blue_paint_mask,
    group_active_channels,
    load_rgb,
    luminance,
    luminance_delta_mask,
    make_diffuse_target,
    masked_gaussian_blur,
    process,
    process_arrays,
    resize_to,
    rgb_to_ycbcr,
    run_channel_pipeline,
    sample_palette_skin_rgb,
    save_rgb,
    ycbcr_to_rgb,
)
from .infill import apply_extrapolation_blur, extend_texture_boundaries

__all__ = [
    "DEFAULT_REGION_PALETTE",
    "DEFAULT_SELF_LOCALITY_RADIUS",
    "GATE_MODES",
    "MaskChannel",
    "apply_blend_group",
    "apply_blending_radius",
    "apply_extrapolation_blur",
    "apply_mask_channel",
    "build_correction_target",
    "build_local_diffuse_target",
    "build_region_gate",
    "color_id_mask",
    "composite_correction_targets",
    "composite_skin_envelope",
    "composite_weights",
    "compute_channel_gate",
    "compute_channel_soft_mask",
    "correct_region",
    "extend_texture_boundaries",
    "extract_blue_paint_mask",
    "group_active_channels",
    "load_rgb",
    "luminance",
    "luminance_delta_mask",
    "make_diffuse_target",
    "masked_gaussian_blur",
    "process",
    "process_arrays",
    "resize_to",
    "rgb_to_ycbcr",
    "run_channel_pipeline",
    "sample_palette_skin_rgb",
    "save_rgb",
    "ycbcr_to_rgb",
]
